version: "2"
services:
 consul-registrator:
  labels:
    io.rancher.sidekicks: consul,consul-data
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  restart: always
  command:
    - -internal
    - -deregister=always
    - -cleanup=true
    - -resync=5
    - consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
    - consul
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  stdin_open: true
 consul:
  ports:
    - 8300:8300/tcp
    - 8301:8301/tcp
    - 8301:8301/udp
    - 8302:8302/tcp
    - 8302:8302/udp
    - 8400:8400/tcp
    - 8500:8500/tcp
    - 8600:8600/tcp
    - 8600:8600/udp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.dns: true
  tty: true
  restart: always
  command:
     - /bin/sh
     - -c
     - |
       curl --url https://raw.githubusercontent.com/Galucinogen/consul-catalog/master/kubernetes-templates/consul-registrator/1/files/server.json --output /tmp/server.json
       curl --url https://raw.githubusercontent.com/Galucinogen/consul-catalog/master/kubernetes-templates/consul-registrator/1/files/server-ca.crt --output /tmp/server-ca.crt
       curl --url https://raw.githubusercontent.com/Galucinogen/consul-catalog/master/kubernetes-templates/consul-registrator/1/files/agent_4.key --output /tmp/agent_4.key
       curl --url https://raw.githubusercontent.com/Galucinogen/consul-catalog/master/kubernetes-templates/consul-registrator/1/files/agent_4.crt --output /tmp/agent_4.crt
       consul agent -retry-join ${consul_server} -recursor=169.254.169.250 -client=0.0.0.0 -config-file=/tmp/server.json
  environment:
    CONSUL_LOCAL_CONFIG: "{\"leave_on_terminate\": true, \"datacenter\": \"${consul_datacenter}\"}"
    CONSUL_BIND_INTERFACE: ${consul_bind_interface}
  volumes_from:
    - consul-data
  image: consul:latest
  stdin_open: true
 consul-data:
  image: consul:latest
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.global: 'true'
    io.rancher.container.start_once: true
  volumes:
    - /consul/data
  entrypoint: /bin/true
